# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c13f5131d76e4c0bfbf1a34577be42b"
name = "Vuba-Surcharges"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_cart_transforms, write_inventory"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
