query CartTransformRunInput {
  cart {
    buyerIdentity {
      customer {
        hasAnyTag(tags: ["Distributor"])
      }
    }
    lines {
      id
      quantity
      attribute(key: "_added_by_vuba_webhook") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
          product {
            handle
            inAnyCollection(ids: ["gid://shopify/Collection/446838440227", "gid://shopify/Collection/703363776899"])
          }
        }
      }
    }
  }
  shop {
    metafield(namespace: "vuba_surcharges", key: "fee_variant_id") {
      value
    }
  }
}